#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.
#Requirements:
#Accepts a string as an argument
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times

# Check if an argument is provided
if [ $# -eq 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network $0 {IP_ADDRESS}"
    exit 1
elif [$# -gt 1]; then
	echo "Usage: 5-is_the_host_on_the_network $0 {IP_ADDRESS}"
	exit
else
	ping "#1" -c 5
fi
